### ISSUE TITLE
Battery draining very fast after about 85% (Only 2 hours battery life total)

### ISSUE THREAD

**Issue by jt1900jt** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#19]
So I have the exact same model as stonevil and my battery is draining ridiculous fast after about 70 percent. Here are some measurements I took:

time 0: 100%
50 minutes: 85%
56 minutes: 84%
1 hour and 7 minutes: 72%
1 hour and 13 minutes: 63%
1 hour and 18 minutes: 57%
1 hour and 35 minutes: 26%
1 hour and 45 minutes: 23%
1 hour and 47 minutes 20%

Total I'm barely getting 2 hours of battery life. I've attached my EFI, but I'm not entirely sure what's going on.
[EFI.zip](https://github.com/stonevil/Razer_Blade_Advanced_early_2019_Hackintosh/files/3595161/EFI.zip)

edit: issue is fixed thanks to the patches provided by doubleyoustew below. Thanks my guy!

**Comment by k-sym** [comment]
Just to confirm it's not the same as another issue, there is no change in power state? Is this from cold, booted and running without the charger being plugged in, or is it when you remove from power and keep working?

My power issue is always from a power state change. If I reboot, then it's all normal until the device sleeps.

**Comment by bhagirathbhard** [comment]
I can concur having similar battery drain if not worse. I am assuming it has something to do with the Audio Power leak @stonevil was talking about.

**Comment by soerenkampschroer** [comment]
Same thing here @ksymmonds

Mine gets really warm and the fans kick in when it wakes from sleep. CPU usage is super low, it clocks at 0.8ghz and CPU temps are at about 50C so I doubt that's it. Definitely a sleep/power management issue of some sort. Maybe the dGPU kicks back in even though it should be disabled? 

Anyway, try not to use sleep when on battery for the time being or restart after sleeping and see if the issue persists. Right now I'm at 35% and 1:56h remaining (not really accurate but at 100% battery I get way less then that if I wake it from sleep).

**Comment by stonevil** [comment]
Ok. So. I do not have anymore (since August last year) access to RBA.
Last staff I discovered is some architecture issues its RBA logic board. It's doesn't matter if you disable Nvidia GPU in BIOS or in SSDT, etc. GPU still consume power. So, basically there are no way to improve power consumption.

You should have about 3.5-5h on battery in macOS depends on CPU, etc. load.

**Comment by soerenkampschroer** [comment]
@stonevil I'm fine with the battery life I'm getting on a fresh boot (3.5 - 4.5 hours). The problem is that the dGPU seems turn back on after sleeping and then it's more like 1 - 1.5 hours. I posted on tonymac as well but so far no replies.

**Comment by boyuanx** [comment]
It's still an issue with the latest March BIOS, not a dealbreaker but a real bummer.

**Comment by doubleyoustew** [comment]
I fixed this recently. Apply the following patches and add the ssdts from my repo. Make sure to remove any other GPU patching you did before.

**2018 model**
- Add SSDT-DDGPU.aml and SSDT-PTSWAK.aml
- Apply patches _PTS to ZPTS and _WAK to ZWAK

**Early 2019 model**
Do the above and additionally add:
- SSDT-RTEC.aml
- RTEC to XTEC patch

That should keep the dGPU disabled and save a ton of energy. The problem is that there are errors in the DSDT when waking up from sleep. The method RTEC will fail because Local0 is undefined.

The patches can be downloaded from here:
https://github.com/doubleyoustew/Razer-Blade-15/tree/master/Src/Hotpatches/dGPU

**Comment by boyuanx** [comment]
@doubleyoustew Thank you! Those SSDTs work perfectly for disabling dGPU even after wake. 

Another question, if you don't mind =) : My trackpad does not work with any version newer than VoodooI2C v2.2 and I've opened up an issue with them: https://github.com/VoodooI2C/VoodooI2C/issues/319

Do you have any insights? I tried your trackpad SSDTs + hot-patch and while the errors mentioned in the issue go away, my trackpad is completely dead, which is very odd since all logs indicate the trackpad has been successfully registered.

**Comment by doubleyoustew** [comment]
@boyuanx My trackpad is working pretty well now honestly with the latest VoodooI2C. I'm still on Mojave however. One more reason not to upgrade to Catalina I guess.

Props to you for making the video and manually typing the logs haha. It's really annoying that you can't check back on the boot log.

You could try looking for ACPI errors with the following command:

`log show --predicate "processID == 0" --start $(date "+%Y-%m-%d") --debug | grep -i  AppleACPIPlatform`

Could be that something fails to execute and the trackpad is not properly activated. There is also an app called GenI2C that has some diagnostic capabilities. Might be worth a try.

I just noticed that you are using the mid 2019 version of the blade. The trackpad patches in my repo are for the early 2019 model, so I can't guarantee they work for yours. They _should_ work but without checking your DSDT against the patches I can't say for sure.

**Comment by jt1900jt** [comment]
Issue is resolved by the patch doubleyoustew posted above!
